// Any copyright is dedicated to the Public Domain.
// http://creativecommons.org/publicdomain/zero/1.0/

// Generator for the --interpretBitwise regression corpus.
//
// These tests exist to check that Gobra agrees with Go about what bitwise operations compute, so
// the expected values must not be written by hand. Every value below is produced by evaluating the
// operation in Go at the real type: the generic helpers are instantiated at int8, uint32, and so
// on, so `x << s` here is exactly the shift the compiler emits for that type, wrap-around and all.
//
// Regenerate with:
//
//	cd tools/bitvector-gen
//	go run . -out ../../src/test/resources/regressions/features/integers/bitvectors
//
// and review the diff. The generated files are committed, so the test suite needs no Go toolchain.
// This generator deliberately lives outside src/test/resources/regressions: everything under that
// directory is picked up as a test case, .go files included.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// Shift counts, including at and beyond every width. Go places no upper limit on a shift count:
// the operand is shifted one bit at a time, so any count at or above the width saturates (to 0, or
// to -1 for an arithmetic shift of a negative value). This is the case most likely to diverge from
// a bitvector encoding, where the shift amount is itself a bitvector and a large count would wrap.
var shiftCounts = []uint{0, 1, 7, 8, 31, 32, 63, 64, 100, 1000}

type integer interface {
	~int8 | ~int16 | ~int32 | ~int64 | ~uint8 | ~uint16 | ~uint32 | ~uint64
}

// Each of these is the genuine Go operation at type T -- that is the oracle.
func and[T integer](x, y T) T    { return x & y }
func or[T integer](x, y T) T     { return x | y }
func xor[T integer](x, y T) T    { return x ^ y }
func clear[T integer](x, y T) T  { return x &^ y }
func not[T integer](x T) T       { return ^x }
func shl[T integer](x T, s uint) T { return x << s }
func shr[T integer](x T, s uint) T { return x >> s }

// emit renders one .gobra file for the Go type named goType, using the given operand corpus.
func emit(dir, goType string, operands []string, vals func(i int) string,
	binop func(i, j int) (string, string, string, string),
	unop func(i int) string,
	shifts func(i int, s uint) (string, string)) error {

	var b strings.Builder
	p := func(format string, a ...interface{}) { fmt.Fprintf(&b, format, a...) }

	p("// Any copyright is dedicated to the Public Domain.\n")
	p("// http://creativecommons.org/publicdomain/zero/1.0/\n\n")
	p("// ##(--interpretBitwise)\n\n")
	p("// GENERATED by gen/main.go -- do not edit by hand.\n")
	p("//\n")
	p("// Every expected value was computed by the Go compiler at type %s, so a failure here means\n", goType)
	p("// Gobra and Go disagree about what a bitwise operation evaluates to.\n")
	p("package bitvectors\n\n")

	p("decreases\nfunc binops_%s(x %s, y %s) {\n", goType, goType, goType)
	for i := range operands {
		for j := range operands {
			a, o, x, c := binop(i, j)
			p("\tif x == %s && y == %s {\n", vals(i), vals(j))
			p("\t\tassert x & y == %s\n", a)
			p("\t\tassert x | y == %s\n", o)
			p("\t\tassert x ^ y == %s\n", x)
			p("\t\tassert x &^ y == %s\n", c)
			p("\t}\n")
		}
	}
	p("}\n\n")

	p("decreases\nfunc unop_%s(x %s) {\n", goType, goType)
	for i := range operands {
		p("\tif x == %s {\n\t\tassert ^x == %s\n\t}\n", vals(i), unop(i))
	}
	p("}\n\n")

	p("decreases\nfunc shifts_%s(x %s, s uint) {\n", goType, goType)
	for i := range operands {
		for _, s := range shiftCounts {
			l, r := shifts(i, s)
			p("\tif x == %s && s == %d {\n", vals(i), s)
			p("\t\tassert x << s == %s\n", l)
			p("\t\tassert x >> s == %s\n", r)
			p("\t}\n")
		}
	}
	p("}\n")

	return os.WriteFile(filepath.Join(dir, "bitvector-"+goType+".gobra"), []byte(b.String()), 0o644)
}

// emitFor wires a concrete type into emit. Keeping it generic is what guarantees the expected
// values come from Go's own evaluation at that type rather than from a hand-written model of it.
func emitFor[T integer](dir, goType string, vs []T) error {
	str := func(v T) string { return fmt.Sprintf("%d", v) }
	names := make([]string, len(vs))
	for i := range vs {
		names[i] = str(vs[i])
	}
	return emit(dir, goType, names,
		func(i int) string { return str(vs[i]) },
		func(i, j int) (string, string, string, string) {
			return str(and(vs[i], vs[j])), str(or(vs[i], vs[j])), str(xor(vs[i], vs[j])), str(clear(vs[i], vs[j]))
		},
		func(i int) string { return str(not(vs[i])) },
		func(i int, s uint) (string, string) { return str(shl(vs[i], s)), str(shr(vs[i], s)) },
	)
}

func main() {
	out := flag.String("out", ".", "directory to write the .gobra files into")
	flag.Parse()

	check := func(err error) {
		if err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
	}

	// Corpora deliberately stay small: every pair becomes four assertions, and bitvector queries
	// are not free. They cover the range edges, the sign boundary, alternating bit patterns, and a
	// couple of arbitrary values.
	check(emitFor(*out, "int8", []int8{0, 1, -1, -128, 127, 0x55, -6, 100}))
	check(emitFor(*out, "uint8", []uint8{0, 1, 255, 0x55, 0xAA, 0xF0, 12, 200}))
	check(emitFor(*out, "int16", []int16{0, 1, -1, -32768, 32767, 0x5555, -1234}))
	check(emitFor(*out, "uint16", []uint16{0, 1, 65535, 0x5555, 0xAAAA, 0xFF00}))
	check(emitFor(*out, "int32", []int32{0, 1, -1, -2147483648, 2147483647, 0x010203}))
	check(emitFor(*out, "uint32", []uint32{0, 1, 4294967295, 0x55555555, 0xDEADBEEF, 66051}))
	check(emitFor(*out, "int64", []int64{0, 1, -1, -9223372036854775808, 9223372036854775807}))
	check(emitFor(*out, "uint64", []uint64{0, 1, 18446744073709551615, 0xDEADBEEF}))
}
