// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2011-2021 ETH Zurich.

package viper.gobra.translator.encodings.maps

import org.bitbucket.inkytonik.kiama.==>
import viper.gobra.ast.{internal => in}
import viper.gobra.reporting.BackTranslator.RichErrorMessage
import viper.gobra.reporting._
import viper.gobra.theory.Addressability
import viper.gobra.theory.Addressability.{Exclusive, Shared}
import viper.gobra.translator.Names
import viper.gobra.translator.encodings.combinators.LeafTypeEncoding
import viper.gobra.translator.encodings.maps.MapEncoding.{checkKeyComparability, comparabilityErrorT, repeatedKeyErrorT}
import viper.gobra.translator.context.Context
import viper.gobra.translator.util.ViperUtil.synthesized
import viper.gobra.translator.util.{FunctionGenerator, PrimitiveGenerator}
import viper.gobra.translator.util.ViperWriter.CodeLevel._
import viper.gobra.translator.util.ViperWriter.CodeWriter
import viper.gobra.util.Violation
import viper.silver.plugin.standard.termination
import viper.silver.verifier.reasons.AssertionFalse
import viper.silver.verifier.{ErrorReason, errors => err, reasons}
import viper.silver.{ast => vpr}

/**
  * Encoding for Go maps. Unlike slices, maps are not thread-safe;
  * thus, all concurrent accesses to maps must be synchronized. In particular,
  * assigning to different indices of a slice cannot occur in parallel. Besides,
  * obtaining the length of a map requires read permissions because maps may
  * change in size unlike slices, e.g.
  *    m := make(map[int]int)
  *    go f(m) // f(m) sets m[10] to 10
  *    go g(m) // where g(m) computes len(m)
  * This encoding prevents Gobra from verifying this example, which is correct
  * because it contains a race condition.
  *
  * A Go map is encoded as a [[vpr.Ref]] (because `nil` is an admissible value for maps)
  * with a field `underlyingMapField` of Viper type `Map[K, V]` holding its contents.
  *
  * All operations on maps are encoded as applications of the (heap-dependent) pure
  * functions generated by this encoding instead of being inlined. This is essential
  * for triggers: the natural inlined encoding of, e.g., a lookup `m[k]` is a
  * conditional expression (to account for `m` being `nil`), and conditional
  * expressions are not admissible triggers in Viper. As a consequence, any user
  * annotation mentioning a map operation inside a trigger used to be rejected by
  * Viper or resulted in poor triggering behaviour. Because a function application is
  * always an admissible trigger, and because the very same function application is
  * generated whether or not the expression occurs in a trigger, terms occurring in
  * triggers now match the terms occurring in the bodies of quantifiers.
  */
class MapEncoding extends LeafTypeEncoding {
  import viper.gobra.translator.util.TypePatterns._

  /**
    * Translates a type into a Viper type.
    * Both Exclusive and Shared maps are encoded as vpr.Ref because nil is an admissible value for maps
    */
  override def typ(ctx: Context): in.Type ==> vpr.Type = {
    case ctx.Map(_, _) / Exclusive => mapType
    case ctx.Map(_, _) / Shared => vpr.Ref
  }

  private val mapType: vpr.Type = vpr.Ref

  /**
    * Encodes expressions as values that do not occupy some identifiable location in memory.
    * R[ nil(map[K]V°) ] -> null
    * R[ dflt(map[K]V°) ] -> null
    * R[ len(e: map[K]V) ] -> mapCardinality$K$V([ e ])
    * R[ (e: map[K]V)[idx] ] -> assert(isComparable([ idx ])); mapLookup$K$V([ e ], [ idx ])
    * R[ keySet(e: map[K]V) ] -> mapKeySet$K$V([ e ])
    * R[ valueSet(e: map[K]V) ] -> mapValueSet$K$V([ e ])
    * R[ k in (e: map[K]V) ] -> assert(isComparable([ k ])); mapContains$K$V([ e ], [ k ])
    * R[ dict(e: map[K]V) ] -> getCorrespondingMap([ e ])
    */
  override def expression(ctx: Context): in.Expr ==> CodeWriter[vpr.Exp] = {
    def goE(x: in.Expr): CodeWriter[vpr.Exp] = ctx.expression(x)

    default(super.expression(ctx)) {
      case (exp: in.DfltVal) :: ctx.Map(_, _) / Exclusive => unit(withSrc(vpr.NullLit(), exp))

      case (exp: in.NilLit) :: ctx.Map(_, _) / Exclusive => unit(withSrc(vpr.NullLit(), exp))

      case l@in.Length(exp :: ctx.Map(keys, values)) =>
        val (pos, info, errT) = l.vprMeta
        for {
          e <- goE(exp)
          app = mapCardinalityGenerator(Vector(e), (keys, values))(pos, info, errT)(ctx)
          res <- mapFuncApp(app)
        } yield res

      case l@in.IndexedExp(m :: ctx.Map(keys, values), idx, _) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- goE(m)
          vIdx <- goE(idx)
          isComp <- checkKeyComparability(idx)(ctx)
          app = mapLookupGenerator(Vector(vMap, vIdx), (keys, values))(pos, info, errT)(ctx)
          lookup <- mapFuncApp(app)
          res <- assert(isComp, lookup, comparabilityErrorT)(ctx)
        } yield res

      case l@in.Contains(key, m :: ctx.Map(keys, values)) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- goE(m)
          vKey <- goE(key)
          isComp <- checkKeyComparability(key)(ctx)
          app = mapContainsGenerator(Vector(vMap, vKey), (keys, values))(pos, info, errT)(ctx)
          contains <- mapFuncApp(app)
          res <- assert(isComp, contains, comparabilityErrorT)(ctx)
        } yield res

      case k@in.MapKeys(mapExp :: ctx.Map(keys, values), _) =>
        val (pos, info, errT) = k.vprMeta
        for {
          vMap <- goE(mapExp)
          app = mapKeySetGenerator(Vector(vMap), (keys, values))(pos, info, errT)(ctx)
          res <- mapFuncApp(app)
        } yield res

      case v@in.MapValues(mapExp :: ctx.Map(keys, values), _) =>
        val (pos, info, errT) = v.vprMeta
        for {
          vMap <- goE(mapExp)
          app = mapValueSetGenerator(Vector(vMap), (keys, values))(pos, info, errT)(ctx)
          res <- mapFuncApp(app)
        } yield res

      case in.MapConversion(exp :: ctx.Map(keys, values)) =>
        getCorrespondingMap(exp, keys, values)(ctx)
    }
  }

  /**
    * Encodes expressions when they occur as the top-level expression in a trigger.
    * These cases coincide with the encoding of the corresponding expressions (see
    * [[expression]]), except that the runtime checks performed by the expression
    * encoding (e.g., that the key of a lookup is comparable) are omitted, as no
    * checks may be emitted for a trigger. Emitting the very same terms as
    * [[expression]] does is crucial: otherwise, the terms of a trigger would never
    * match the terms in the body of the quantifier they belong to.
    *   { m[i] } -> { mapLookup$K$V([ m ], [ i ]) }
    *   { k in m } -> { mapContains$K$V([ m ], [ k ]) }
    *   { k in domain(m) } -> { [ k ] in mapKeySet$K$V([ m ]) }
    *   { k in range(m) } -> { [ k ] in mapValueSet$K$V([ m ]) }
    */
  override def triggerExpr(ctx: Context): in.TriggerExpr ==> CodeWriter[vpr.Exp] = {
    default(super.triggerExpr(ctx)) {
      case l@in.IndexedExp(m :: ctx.Map(keys, values), idx, _) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- ctx.expression(m)
          vIdx <- ctx.expression(idx)
        } yield mapLookupGenerator(Vector(vMap, vIdx), (keys, values))(pos, info, errT)(ctx)

      case l@in.Contains(key, m :: ctx.Map(keys, values)) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- ctx.expression(m)
          vKey <- ctx.expression(key)
        } yield mapContainsGenerator(Vector(vMap, vKey), (keys, values))(pos, info, errT)(ctx)

      case l@in.Contains(key, in.MapKeys(m :: ctx.Map(keys, values), _)) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- ctx.expression(m)
          vKey <- ctx.expression(key)
          keySet = mapKeySetGenerator(Vector(vMap), (keys, values))(pos, info, errT)(ctx)
        } yield vpr.AnySetContains(vKey, keySet)(pos, info, errT)

      case l@in.Contains(key, in.MapValues(m :: ctx.Map(keys, values), _)) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- ctx.expression(m)
          vKey <- ctx.expression(key)
          valueSet = mapValueSetGenerator(Vector(vMap), (keys, values))(pos, info, errT)(ctx)
        } yield vpr.AnySetContains(vKey, valueSet)(pos, info, errT)
    }
  }

  /**
    * Encodes the allocation of a new map
    *  [r := make(map[T1]T2, n)] ->
    *    asserts 0 <= [n]
    *    var a Ref := new(underlyingMapField)
    *    inhales len(m) == 0, where m is the underlying map of a
    *    [r] := a
    *
    *  [v, ok := exp[idx] ->
    *     assert isComparable([ idx ])
    *     var res [T1]
    *     var ok' Bool
    *     res := mapLookup$K$V([ exp ], [ idx ])
    *     ok' := mapContains$K$V([ exp ], [ idx ])
    *     [v] := res
    *     [ok] := ok'
    *
    *  R[ map[K]V { idx1: v1 ... idxn: vn } ] ->
    *     e s.t. getCorrespondingMap(e) == { [idx1]: [v1] ... [idxn]: [vn] } (also checks that the values of keys are all
    *     distinct and throws an error if not)
    */
  override def statement(ctx: Context): in.Stmt ==> CodeWriter[vpr.Stmt] = {
    def goE(x: in.Expr): CodeWriter[vpr.Exp] = ctx.expression(x)
    def goT(t: in.Type): vpr.Type = ctx.typ(t)

    default(super.statement(ctx)) {
      case makeStmt@in.MakeMap(target, t@in.MapT(keys, values, _), makeArg) =>
        val (pos, info, errT) = makeStmt.vprMeta

        // Runtime check asserting 0 <= [n]
        val runtimeCheck = makeArg.toVector map { n =>
          for {
            nVpr <- goE(n)
            runtimeCheckExp = vpr.LeCmp(vpr.IntLit(0)(pos, info, errT), nVpr)(pos, info, errT)
          } yield vpr.Exhale(runtimeCheckExp)(pos, info, errT)
        }

        seqn(
          for {
            checks <- sequence(runtimeCheck)
            _ <- write(checks: _*)
            _ <- if (checks.nonEmpty) errorT {
              case e@err.ExhaleFailed(Source(info), _, _) if e.causedBy(checks(0)) =>
                MapMakePreconditionError(info)
            } else unit(())

            mapVar = in.LocalVar(ctx.freshNames.next(), t.withAddressability(Exclusive))(makeStmt.info)
            mapVarVpr = ctx.variable(mapVar)
            _ <- local(mapVarVpr)

            correspondingMap <- getCorrespondingMap(mapVar, keys, values)(ctx)
            _ <- write(vpr.NewStmt(mapVarVpr.localVar, Seq(underlyingMapField(ctx)(keys, values)))(pos, info, errT))
            _ <- write(vpr.Inhale(vpr.EqCmp(correspondingMap, vpr.EmptyMap(goT(keys), goT(values))(pos, info, errT))(pos, info, errT))(pos, info, errT))
            ass <- ctx.assignment(in.Assignee.Var(target), mapVar)(makeStmt)
          } yield ass
        )

      case l@in.SafeMapLookup(resTarget, successTarget, indexedExp@in.IndexedExp(_, _, _)) =>
        val (pos, info, errT) = l.vprMeta
        val res = in.LocalVar(ctx.freshNames.next(), indexedExp.typ.withAddressability(Addressability.Exclusive))(l.info)
        val vprRes = ctx.variable(res)
        val ok = in.LocalVar(ctx.freshNames.next(), in.BoolT(Addressability.Exclusive))(l.info)
        val vprOk = ctx.variable(ok)

        seqn(
          for {
            _ <- local(vprRes)
            _ <- local(vprOk)

            (lookupVal, okCond) <- goMapLookup(indexedExp)(ctx)
            lookupValAss = vpr.LocalVarAssign(vprRes.localVar, lookupVal)(pos, info, errT)
            okAss = vpr.LocalVarAssign(vprOk.localVar, okCond)(pos, info, errT)
            _ <- write(okAss)
            _ <- write(lookupValAss)

            resAss <- ctx.assignment(in.Assignee.Var(resTarget), res)(l)
            _ <- write(resAss)

            okAss <- ctx.assignment(in.Assignee.Var(successTarget), ok)(l)
          } yield okAss
        )

      case lit: in.NewMapLit =>
        val (pos, info, errT) = lit.vprMeta
        val res = in.LocalVar(ctx.freshNames.next(), lit.typ.withAddressability(Exclusive))(lit.info)
        val vRes = ctx.variable(res)

        for {
          mapletList <- sequence(lit.entries.toVector.map {
            case (key, value) => for {
              kVpr <- goE(key)
              isCompKey <- checkKeyComparability(key)(ctx)
              k <- assert(isCompKey, kVpr, comparabilityErrorT)(ctx) // key must be comparable
              v <- goE(value)
            } yield vpr.Maplet(k, v)(pos, info, errT)
          })

          underlyingMap <- if (mapletList.nonEmpty) {
            // silver assumes that the argument of ExplicitMap is not empty
            val keySeq = mapletList map (_.key)
            // checks whether all keys are distinct
            val checkAllDiffKeys = vpr.EqCmp(
              vpr.AnySetCardinality(vpr.ExplicitSet(keySeq)(pos, info, errT))(pos, info, errT),
              vpr.SeqLength(vpr.ExplicitSeq(keySeq)(pos, info, errT))(pos, info, errT)
            )(pos, info, errT)
            assert(checkAllDiffKeys, vpr.ExplicitMap(mapletList)(pos, info, errT), repeatedKeyErrorT)(ctx)
          } else {
            unit(vpr.EmptyMap(goT(lit.keys), goT(lit.values))(pos, info, errT))
          }
          _ <- local(vRes)
          correspondingMap <- getCorrespondingMap(res, lit.keys, lit.values)(ctx)
          // inhale acc(res.underlyingMapField)
          _ <- write(
            vpr.Inhale(
              vpr.FieldAccessPredicate(
                vpr.FieldAccess(vRes.localVar, underlyingMapField(ctx)(lit.keys, lit.values))(pos, info, errT),
                Some(vpr.FullPerm()(pos, info, errT))
              )(pos, info, errT))(pos, info, errT))
          // inhale getCorrespondingMap(res) == underlyingMap; recall that underlyingMap == ExplicitMap(mapletList)
          _ <- write(vpr.Inhale(vpr.EqCmp(underlyingMap, correspondingMap)(pos, info, errT))(pos, info, errT))
          ass <- ctx.assignment(in.Assignee.Var(lit.target), res)(lit)
        } yield ass
    }
  }

  /**
    * Encodes whether a value is comparable or not.
    */
  override def isComparable(ctx: Context): in.Expr ==> Either[Boolean, CodeWriter[vpr.Exp]] = {
    case _ :: ctx.Map(_, _) => Left[Boolean, CodeWriter[vpr.Exp]](false)
  }

  /**
    * Encodes an assignment.
    * [ mapExp[idx] = newVal ] ->
    *     var m: Map[ [k], [v] ]
    *     m = [mapExp].underlyingMapField
    *     [mapExp].underlyingMapField := m[ [idx] = [newVal] ]
    */
  override def assignment(ctx: Context): (in.Assignee, in.Expr, in.Node) ==> CodeWriter[vpr.Stmt] = {

    default(super.assignment(ctx)) {
      case (in.Assignee(in.IndexedExp(m :: ctx.Map(keys, values), idx, _)), rhs, src) =>
        val (pos, info, errT) = src.vprMeta
        seqn(
          for {
            isCompKey <- MapEncoding.checkKeyComparability(idx)(ctx)
            _ <- assert(isCompKey, comparabilityErrorT) // key must be comparable
            vRhs <- ctx.expression(rhs)
            vIdx <- ctx.expression(idx)
            correspondingMapM <- getCorrespondingMap(m, keys, values)(ctx)
          } yield vpr.FieldAssign(correspondingMapM, vpr.MapUpdate(correspondingMapM, vIdx, vRhs)(pos, info, errT))(pos, info, errT)
        )
    }
  }

  /**
    * Encodes assertions.
    * [acc(m: map[K]V, perm)] -> acc([m].underlyingMapField, [perm])
    */
  override def assertion(ctx: Context): in.Assertion ==> CodeWriter[vpr.Exp] = {
    def goE(x: in.Expr): CodeWriter[vpr.Exp] = ctx.expression(x)

    default(super.assertion(ctx)) {
      case n@in.Access(in.Accessible.ExprAccess(exp :: ctx.Map(keys, values)), perm) =>
        val (pos, info, errT) = n.vprMeta
        for {
          vE <- goE(exp)
          vP <- goE(perm)
        } yield vpr.FieldAccessPredicate(
          vpr.FieldAccess(vE, underlyingMapField(ctx)(keys, values))(pos, info, errT),
          Some(vP)
        )(pos, info, errT)
    }
  }

  override def finalize(addMemberFn: vpr.Member => Unit): Unit = {
    underlyingMapFieldGenerator.finalize(addMemberFn)
    mapKeySetGenerator.finalize(addMemberFn)
    mapValueSetGenerator.finalize(addMemberFn)
    mapCardinalityGenerator.finalize(addMemberFn)
    mapContainsGenerator.finalize(addMemberFn)
    mapLookupGenerator.finalize(addMemberFn)
  }

  /**
    * Builds the expression `[exp].underlyingMapField`
    */
  private def getCorrespondingMap(exp: in.Expr, keys: in.Type, values: in.Type)(ctx: Context): CodeWriter[vpr.FieldAccess] = {
    def goE(x: in.Expr): CodeWriter[vpr.Exp] = ctx.expression(x)

    for {
      vExp <- goE(exp)
      res = withSrc(vpr.FieldAccess(vExp, underlyingMapField(ctx)(keys, values)), exp)
    } yield res
  }

  /**
    * Registers an error transformer that back-translates a failing precondition of one of the
    * pure functions generated by this encoding. All of these functions have a single non-trivial
    * precondition, namely that the caller holds some permission to the underlying map, so the
    * only reason such a precondition may fail is a lack of permissions.
    */
  private def mapFuncApp(app: vpr.FuncApp): CodeWriter[vpr.Exp] =
    for {
      _ <- errorT({
        case e@err.PreconditionInAppFalse(Source(info), reasons.InsufficientPermission(_), _) if e causedBy app =>
          InsufficientPermissionToMapError(info)
      })
    } yield app

  /**
    * Computes the result of looking up a value in an indexed expression and a bool expression asserting
    * whether the key is in the map. The comparability of the key is checked once for both expressions.
    */
  private def goMapLookup(lookupExp: in.IndexedExp)(ctx: Context): CodeWriter[(vpr.Exp, vpr.Exp)] = {
    def goE(x: in.Expr): CodeWriter[vpr.Exp] = ctx.expression(x)

    lookupExp match {
      case l@in.IndexedExp(exp :: ctx.Map(keys, values), idx, _) =>
        val (pos, info, errT) = l.vprMeta
        for {
          vMap <- goE(exp)
          vIdx <- goE(idx)
          isComp <- checkKeyComparability(idx)(ctx)
          _ <- assert(isComp, comparabilityErrorT) // key must be comparable
          lookupApp = mapLookupGenerator(Vector(vMap, vIdx), (keys, values))(pos, info, errT)(ctx)
          lookupRes <- mapFuncApp(lookupApp)
          containsApp = mapContainsGenerator(Vector(vMap, vIdx), (keys, values))(pos, info, errT)(ctx)
          containsRes <- mapFuncApp(containsApp)
        } yield (lookupRes, containsRes)
      case _ => Violation.violation(s"unexpected case reached")
    }
  }

  private def internalMemberName(prefix: String, k: in.Type, v: in.Type): String = {
    val kN = Names.serializeType(k)
    val vN = Names.serializeType(v)
    s"$prefix$$$kN$$$vN"
  }

  /**
    * Field of the corresponding map type
    */
  private val underlyingMapFieldPrefix: String = "underlyingMapField"
  private def underlyingMapField(ctx: Context)(k: in.Type, v: in.Type): vpr.Field = {
    val name = internalMemberName(underlyingMapFieldPrefix, k, v)
    val vprK = ctx.typ(k)
    val vprV = ctx.typ(v)
    underlyingMapFieldGenerator(name, vprK, vprV)
  }

  private val underlyingMapFieldGenerator: PrimitiveGenerator.PrimitiveGenerator[(String, vpr.Type, vpr.Type), vpr.Field] =
    PrimitiveGenerator.simpleGenerator {
      case (name: String, k: vpr.Type, v: vpr.Type) =>
        val f = vpr.Field(name = name, typ = vpr.MapType(k, v))()
        (f, Vector(f))
    }

  /** Declaration of the parameter denoting the map that all generated functions take. */
  private def mapParamDecl(): vpr.LocalVarDecl = vpr.LocalVarDecl("m", mapType)()

  /**
    * Builds the precondition `m != null ==> acc(m.underlyingMapField, wildcard)` shared by all
    * functions generated by this encoding. Notice that no permission is required when `m` is `nil`,
    * matching the fact that operations on `nil` maps are well-defined in Go.
    */
  private def mapAccess(m: vpr.LocalVarDecl, k: in.Type, v: in.Type)(ctx: Context): vpr.Exp =
    vpr.Implies(
      vpr.NeCmp(m.localVar, vpr.NullLit()())(),
      vpr.FieldAccessPredicate(
        vpr.FieldAccess(m.localVar, underlyingMapField(ctx)(k, v))(),
        Some(vpr.WildcardPerm()())
      )()
    )()

  private def terminationMeasure(): vpr.Exp =
    synthesized(termination.DecreasesWildcard(None))("This function is assumed to terminate")

  private val mapKeySetGenerator: FunctionGenerator[(in.Type, in.Type)] = new FunctionGenerator[(in.Type, in.Type)] {
    /**
      * Generates the Viper function computing the set of keys of a map with key type K and value type V:
      *
      * function mapKeySet$K$V(m: Ref): Set[K]
      *   requires m != null ==> acc(m.underlyingMapField$K$V, wildcard)
      *   decreases _
      * { m == null ? Set[K]() : domain(m.underlyingMapField$K$V) }
      */
    override def genFunction(x: (in.Type, in.Type))(ctx: Context): vpr.Function = {
      val (keyT, valueT) = x
      val m = mapParamDecl()
      val field = underlyingMapField(ctx)(keyT, valueT)
      val vprKeyT = ctx.typ(keyT)
      val resultT = vpr.SetType(vprKeyT)
      vpr.Function(
        name = internalMemberName("mapKeySet", keyT, valueT),
        formalArgs = Seq(m),
        typ = resultT,
        pres = Seq(mapAccess(m, keyT, valueT)(ctx), terminationMeasure()),
        posts = Seq.empty,
        body = Some(
          vpr.CondExp(
            vpr.EqCmp(m.localVar, vpr.NullLit()())(),
            vpr.EmptySet(vprKeyT)(),
            vpr.MapDomain(vpr.FieldAccess(m.localVar, field)())()
          )()
        )
      )()
    }
  }

  private val mapValueSetGenerator: FunctionGenerator[(in.Type, in.Type)] = new FunctionGenerator[(in.Type, in.Type)] {
    /**
      * Generates the Viper function computing the set of values of a map with key type K and value type V:
      *
      * function mapValueSet$K$V(m: Ref): Set[V]
      *   requires m != null ==> acc(m.underlyingMapField$K$V, wildcard)
      *   ensures  m == null ==> result == Set[V]()
      *   ensures  m != null ==> result == range(m.underlyingMapField$K$V)
      *   ensures  forall v: V :: { v in result } v in result ==>
      *              exists k: K :: mapContains$K$V(m, k) && mapLookup$K$V(m, k) == v
      *   decreases _
      *
      * Unlike the other functions generated by this encoding, this one is left abstract on purpose.
      * The last postcondition provides the witness of a value's key in terms of `mapLookup`. It is
      * required to prove assertions such as `v in range(m) ==> exists k :: m[k] == v`: Viper's map
      * axiomatization provides a Skolem function for the key of a value in the range of a map, but
      * that Skolem function ranges over the *underlying* map, and hence never gives rise to a
      * `mapLookup` term. Stating the same fact as the postcondition of a function with a body is
      * not an option, as proving it would require exactly the `mapLookup` term that is missing.
      */
    override def genFunction(x: (in.Type, in.Type))(ctx: Context): vpr.Function = {
      val (keyT, valueT) = x
      val m = mapParamDecl()
      val field = underlyingMapField(ctx)(keyT, valueT)
      val vprKeyT = ctx.typ(keyT)
      val vprValueT = ctx.typ(valueT)
      val resultT = vpr.SetType(vprValueT)
      val result = vpr.Result(resultT)()
      val vDecl = vpr.LocalVarDecl("v", vprValueT)()
      val kDecl = vpr.LocalVarDecl("k", vprKeyT)()
      val witness = vpr.Exists(
        Seq(kDecl),
        Seq.empty,
        vpr.And(
          mapContainsGenerator(Vector(m.localVar, kDecl.localVar), x)()(ctx),
          vpr.EqCmp(mapLookupGenerator(Vector(m.localVar, kDecl.localVar), x)()(ctx), vDecl.localVar)()
        )()
      )()
      vpr.Function(
        name = internalMemberName("mapValueSet", keyT, valueT),
        formalArgs = Seq(m),
        typ = resultT,
        pres = Seq(mapAccess(m, keyT, valueT)(ctx), terminationMeasure()),
        posts = Seq(
          vpr.Implies(
            vpr.EqCmp(m.localVar, vpr.NullLit()())(),
            vpr.EqCmp(result, vpr.EmptySet(vprValueT)())()
          )(),
          vpr.Implies(
            vpr.NeCmp(m.localVar, vpr.NullLit()())(),
            vpr.EqCmp(result, vpr.MapRange(vpr.FieldAccess(m.localVar, field)())())()
          )(),
          vpr.Forall(
            Seq(vDecl),
            Seq(vpr.Trigger(Seq(vpr.AnySetContains(vDecl.localVar, result)()))()),
            vpr.Implies(vpr.AnySetContains(vDecl.localVar, result)(), witness)()
          )()
        ),
        body = None
      )()
    }
  }

  private val mapCardinalityGenerator: FunctionGenerator[(in.Type, in.Type)] = new FunctionGenerator[(in.Type, in.Type)] {
    /**
      * Generates the Viper function computing the cardinality of a map with key type K and value type V:
      *
      * function mapCardinality$K$V(m: Ref): Int
      *   requires m != null ==> acc(m.underlyingMapField$K$V, wildcard)
      *   decreases _
      * { m == null ? 0 : |m.underlyingMapField$K$V| }
      */
    override def genFunction(x: (in.Type, in.Type))(ctx: Context): vpr.Function = {
      val (keyT, valueT) = x
      val m = mapParamDecl()
      val field = underlyingMapField(ctx)(keyT, valueT)
      vpr.Function(
        name = internalMemberName("mapCardinality", keyT, valueT),
        formalArgs = Seq(m),
        typ = vpr.Int,
        pres = Seq(mapAccess(m, keyT, valueT)(ctx), terminationMeasure()),
        posts = Seq.empty,
        body = Some(
          vpr.CondExp(
            vpr.EqCmp(m.localVar, vpr.NullLit()())(),
            vpr.IntLit(0)(),
            vpr.MapCardinality(vpr.FieldAccess(m.localVar, field)())()
          )()
        )
      )()
    }
  }

  private val mapContainsGenerator: FunctionGenerator[(in.Type, in.Type)] = new FunctionGenerator[(in.Type, in.Type)] {
    /**
      * Generates the Viper function deciding whether a key is contained in a map with key type K
      * and value type V:
      *
      * function mapContains$K$V(m: Ref, k: K): Bool
      *   requires m != null ==> acc(m.underlyingMapField$K$V, wildcard)
      *   decreases _
      * { k in mapKeySet$K$V(m) }
      *
      * Defining this function in terms of `mapKeySet` (instead of accessing the underlying map
      * directly) relates `k in m` and `k in domain(m)` syntactically, which the SMT solver would
      * otherwise only relate after a case split on `m == nil`.
      */
    override def genFunction(x: (in.Type, in.Type))(ctx: Context): vpr.Function = {
      val (keyT, valueT) = x
      val m = mapParamDecl()
      val k = vpr.LocalVarDecl("k", ctx.typ(keyT))()
      vpr.Function(
        name = internalMemberName("mapContains", keyT, valueT),
        formalArgs = Seq(m, k),
        typ = vpr.Bool,
        pres = Seq(mapAccess(m, keyT, valueT)(ctx), terminationMeasure()),
        posts = Seq.empty,
        body = Some(
          vpr.AnySetContains(k.localVar, mapKeySetGenerator(Vector(m.localVar), x)()(ctx))()
        )
      )()
    }
  }

  private val mapLookupGenerator: FunctionGenerator[(in.Type, in.Type)] = new FunctionGenerator[(in.Type, in.Type)] {
    /**
      * Generates the Viper function performing a lookup in a map with key type K and value type V:
      *
      * function mapLookup$K$V(m: Ref, k: K): V
      *   requires m != null ==> acc(m.underlyingMapField$K$V, wildcard)
      *   decreases _
      * { m != null && mapContains$K$V(m, k) ? m.underlyingMapField$K$V[k] : [ dflt(V) ] }
      *
      * The redundant conjunct `m != null` makes the lookup of the underlying map trivially
      * well-defined. Notice that the comparability of `k` is *not* a precondition of this
      * function: it is checked at every use site instead, so that a non-comparable key is
      * reported as such rather than as a failing precondition.
      */
    override def genFunction(x: (in.Type, in.Type))(ctx: Context): vpr.Function = {
      val (keyT, valueT) = x
      val m = mapParamDecl()
      val k = vpr.LocalVarDecl("k", ctx.typ(keyT))()
      val field = underlyingMapField(ctx)(keyT, valueT)
      val vprValueT = ctx.typ(valueT)
      val dflt = pure(ctx.expression(in.DfltVal(valueT)(Source.Parser.Internal)))(ctx).res
      vpr.Function(
        name = internalMemberName("mapLookup", keyT, valueT),
        formalArgs = Seq(m, k),
        typ = vprValueT,
        pres = Seq(mapAccess(m, keyT, valueT)(ctx), terminationMeasure()),
        posts = Seq.empty,
        body = Some(
          vpr.CondExp(
            vpr.And(
              vpr.NeCmp(m.localVar, vpr.NullLit()())(),
              mapContainsGenerator(Vector(m.localVar, k.localVar), x)()(ctx)
            )(),
            vpr.MapLookup(vpr.FieldAccess(m.localVar, field)(), k.localVar)(),
            dflt
          )()
        )
      )()
    }
  }
}

object MapEncoding {
  protected[maps] def checkKeyComparability(key: in.Expr)(ctx: Context): CodeWriter[vpr.Exp] = {
    val isComp = ctx.isComparable(key)
    val (pos, info, errT) = key.vprMeta

    isComp match {
      case Left(false) => unit[vpr.Exp](vpr.FalseLit()(pos, info, errT))
      case Left(true) => unit[vpr.Exp](vpr.TrueLit()(pos, info, errT))
      case Right(compExp) => compExp
    }
  }

  protected[maps] val comparabilityErrorT: (Source.Verifier.Info, ErrorReason) => VerificationError = {
    case (info, AssertionFalse(_)) => AssertError(info) dueTo KeyNotComparableReason(info)
    case _ => Violation.violation("unexpected case reached")
  }

  protected[maps] val repeatedKeyErrorT: (Source.Verifier.Info, ErrorReason) => VerificationError = {
    case (info, AssertionFalse(_)) => AssertError(info) dueTo RepeatedMapKeyReason(info)
    case _ => Violation.violation("unexpected case reached")
  }
}
